### ISSUE TITLE
not all collectibles are marked

### ISSUE THREAD

**Issue by shpreetz** [perceptron8/pinky.cr#11] opened 2016-09-15 12:54 UTC
Hi there, 

I just want to let you know, I constantly observed issues while pinky add-on is enabled. I mean part of the collectibles are invisible, please see the pics below.

http://prntscr.com/cial06 
http://prntscr.com/cialb7 - in the first two pics the collectible name is shown when passing the mouse over it, but the collectible is invisible
http://prntscr.com/cialvb - the collectibles were highlighted by a friend but they are invisible

Is this issue known, does it have any workaround?

Thanks for taking some time to investigate the issue,
Regards,
Gica

**Comment by perceptron8** [comment] 2016-09-15 13:02
Duplicate of #5. Check comments for workaround. Thanks for feedback!

**Comment by Silicon71** [comment] 2016-09-15 13:02
Same here, most or all collectibles are invisible since yesterday. The day before yesterday it worked properly.

File loading failed! Please check your network connction, clean your browser cache or try again alter.

**Comment by Silicon71** [comment] 2016-09-15 13:02
File loading failed! Please check your network connction, clean your browser cache or try again alter.

is the

**Closed** 2016-09-15 13:02 UTC

**Comment by perceptron8** [comment] 2016-09-15 14:28
@lilicon71 It's something new indeed. Please subscribe to #12 if you want.
@shpreetz It's possible that you'll encounter #12 too.
