### ISSUE TITLE
Collectibles disappeared

### ISSUE THREAD

**Issue by HerVelizy** [perceptron8/pinky.cr#5] opened 2015-12-20 09:53 UTC
Hello

I have a problem with this extension. Sometimes it works perfectly but sometimes it is awfull. The collectibles images aren't change AND we can't see them at all (we can only find then with magic light).

Other people have the same problem.

**Comment by perceptron8** [comment] 2015-12-20 10:16
Hello

I know about problems. At the same time, I'm not sure I can do anything about that. It's not extension's fault (the code is deadly simple). I believe it's related to the following:

https://bugbase.adobe.com/index.cfm?event=bug&id=3711074
https://code.google.com/p/chromium/issues/detail?id=345160

As you can see, this bug has been fixed around August 2014 (by Chromium people). Until then, redirecting didn't work at all. IMO Flash plugin still doesn't handle all redirections properly (it's non-deterministic, it can be concurrency-related problem).

On the other hand, it may be something else. Maybe I shlould open a new issue? It's difficult to reproduce however, so it could take some time to confirm and resolve.

Until then, the only thing you (and me, and everybody else) can do, is to clear browser's cache whenever any collectible dissapears.

**Comment by perceptron8** [comment] 2015-12-27 08:08
I just noticed that collections are disappearing more likely if TSO is loading in background window. This could be a clue.

**Comment by radeletp** [comment] 2016-03-10 18:50
Sounds like it happens with big load (at loading the island, all collectibles requested at that time are invisible). When afetr you move to another part of the island with less elements to be loaded, then usually it works.

Could it be that the methods onBeforeRequest is not synchronious? Maybe putting directly ["blocking"] inside the onBeforeRequest without the use of the variable would make the trick?

**Comment by perceptron8** [comment] 2016-03-10 19:31
Hi! I'll try to answer your concerns.

It may be that a big load is causing problems. For me, something wrong was happening only when TSO tab was not focused (that's what I meant by "background"). Can't reproduce this on demand, unfortunately. I hope that Chromium / Flash guys will fix this bug by accident (sometimes they break something by accident too, see http://crbug.com/591988 - I had to overcome this with a5f5ec1).

It doesn't matter if `["blocking"]` has an alias (`options`) or not. It's the same. Without a doubt. That's how Javascript and many other languages work.

Callback function is surely handled synchronously. Otherwise it's response couldn't be used to redirect _any_ request.

Anyway, thanks for feedback! :)

**Comment by Miraklefix** [comment] 2016-04-16 03:25
I think i got a solution for the blank collectible problem!
First thing is serversided, where the image is located. There has to be a file "crossdomain.xml"
i think that was the problem you not everywhere can upload and use your picture.
The crossdomain.xml looks like this:
`<?xml version="1.0"?>
<!DOCTYPE cross-domain-policy SYSTEM "http://www.adobe.com/xml/dtds/cross-domain-policy.dtd">
<cross-domain-policy>
    <site-control permitted-cross-domain-policies="all"/>
	<allow-access-from domain="*"/>
	<allow-http-request-headers-from domain="*" headers="*"/>
</cross-domain-policy>`
Flash can´t load Images from not authorized servers.

The second thing i´ve done is to change something on you code at code.js

`var callback = function(details) {
	var otherType = details.type == "other";
	var objectType = details.type == "object";
	if (otherType || objectType) {
		var resource = slice(details.url, "/");
	    var date = new Date();
		if (collectibles.has(resource)) {
			return { "redirectUrl": replacement + "?v=" + date.getTime() };
		}
	}
};
`
I have createt for each collectible a own picture, but i run this local an load images from my own server. it should work same way then with magenta.png

The point is the cache of any client! When the Picture was loaded befor an is allready cached it comes to this problem. So when you add a timestamp there will be everytime placed a new copy of magenta.png in the cache. The Player should then allways see the magenta marker on the map!

Hope it works

greetings from germany
cya

**Comment by perceptron8** [comment] 2016-04-16 05:04
Hi!  I'm glad you wrote. Thanks for your proposal! It's not a solution however as I'll will try to explain.

1. It doesn't look like it's crossdomain.xml. As you surely noticed, there is `<allow-access-from domain="*" />` in every possible crossdomain.xml file used by TSO (including http://dummyimage.com/crossdomain.xml).
2. It doesn't look like it's about cache. Why? Because a) it works most of the time even if cache was used, b) sometimes it doesn't work despite image wasn't cached.

I know that trick with url modification (?v=... part), but I won't use it: mostly because of b). Futhermore, I believe that every piece of static data should be cached if it's possible. It simply should work every time with no problems at all.

I'm still convinced it's concurrency related. See https://chrome.googleblog.com/2015/06/better-battery-life-for-your-laptop.html maybe...?

**Comment by jurgenweber** [comment] 2016-04-25 06:51
it's just stopping worked now.... I can never get them to come up, no matter how many times I refresh or clear cache.

**Comment by perceptron8** [comment] 2016-04-25 06:59
It's still working for me...
1. reinstall Pinky,
2. clear cache,
3. load TSO without switching to other tabs.
Please let me know if it helped.

**Comment by jurgenweber** [comment] 2016-04-25 23:31
as mentioned, I clear cache all the time.
point 3 seems to be the winner.

**Comment by Gildx** [comment] 2016-06-18 07:18
When having Sandman's Powder activated, i noticed that some collectibles dissapeared and only the text appeared when having the luck to find one with the mouse pointer. Removing Sandman's Powder made them visible again and Pinky worked as expected. This is perhaps not a general answer on the issue of dissapearing collectibles, but it is worth to investigate, I believe.

**Comment by Mikepont38230** [comment] 2016-09-06 10:57
cela fait maintenant plusieurs semaines que pincky ne fonctionne que très mal voir même parfois pas du tout. Il manque quasi systématiquement des objets et même en Desinstallant / réinstallant pincky, en nettoyant le cache et autre, rien rien n'y fait ... Il faudrait vraiment envisager quelque chose !

**Comment by Silicon71** [comment] 2016-09-15 13:06
I got an error message since yesterday:

"File loading failed! Please check your network connction, clean your browser cache or try again alter."

Ich did everything mentioned above but nothing worked, even totally new chrome profile did not work.

**Comment by perceptron8** [comment] 2016-09-15 13:14
@Silicon71 I'll check that soon.

**Comment by Silicon71** [comment] 2016-09-15 16:08
Hi Michal,
problem startet yesterday morning (wednesday), tuesday evening it worked 
properly. Maybe it helps.

Thank you for quick reply! Good work!

Regards
Carsten/Silica71


Am 15.09.2016 um 15:14 schrieb Michał Sobkiewicz:

**Comment by Babaluuuuu** [comment] 2016-09-16 11:10
Same with me- it started yesterday evening not to work anymore- and a clear blue window popped up- saying something like: file load not possible...or such cannot remember correctly
I cleared cache around 20 times- it did not work anymore

**Comment by Scotty-36** [comment] 2016-09-28 09:11
I hope, the Problem is solved. Me and a friend in TSO had the Problem, too. 
We created a new Userprofile in Chrome and the problem has gone. Since then we never had the problem again.
I think it's caused by always clearing Cache and Cookies so that Chrome gets into stumbling.
Thanks perceptron8 for this ingenious App :-)

**Comment by perceptron8** [comment] 2016-10-29 08:05
Can't reproduce problem since ed63ed0. I'm going to close this one for now.
Thank you for your help! :-)

**Closed by perceptron8** 2016-10-29 08:05 UTC
Labels: bug
