### ISSUE TITLE
About Pinky

### ISSUE THREAD

**Issue by hellfaxe** [perceptron8/pinky.cr#8] opened 2016-04-01 14:28 UTC
i have a lot of problems wit pinky, a lot of times it not working, only findig a few collestibles. i am using windows 10 and of course google play, i emty the cache every day for best performance.

**Comment by perceptron8** [comment] 2016-04-01 14:37
Duplicate of #5, thanks anyway! If you want to avoid every day cache clearing, see https://github.com/perceptron8/pinky.cr/issues/5#issuecomment-167392167. I'm stuck right now, It's surely not extension's bug. See #5 for details.

**Closed by perceptron8** 2016-04-01 14:37 UTC
